var WEBCHAT_LANG = {
    ru: {
        buttonText: "Нужна помощь?",
        closeChatText: "Посетитель закончил диалог.",
        transferError: "Возникла ошибка при передаче файла :",
        sessionTimeout: "Время сессии истекло. Ваш диалог завершен.",
        //-----prechat panel
        userName: "Имя",
        userNamePlaceholder: "Ваше имя",
        userNameTooltip: "Заполните обязательные поля",
        userTel: "Телефон",
        userTelPlaceholder: "+380",
        userTelTooltip: "Введите номер в правильном формате",
        userQuestion: "Вопрос",
        userQuestionPlaceholder: "Ваш вопрос",
        userLanguage: "Язык общения",
        acceptLabel: "Я принимаю",
        termsLink: "условия пользования",
        closeChatButton: "Закрыть",
        startChatButton: "Начать чат",
        checkbTooltip: "Примите правила пользования",
        //-----chat panel
        resizeTip: "Расширить",
        minimizeTip: "Свернуть",
        newWindowTip: "Открыть в новом окне",
        closeTip: "Завершить диалог",
        soundOffTip: "Выкл. звуковой сигнал",
        soundOnTip: "Вкл. звуковой сигнал",
        soundOffinfo: "Звук выключен",
        soundOninfo: "Звук включен",
        writeComplain: "Пожаловаться",
        sendFileTip: "Отправить файл",
        sendChatTip: "Отправить чат по email",
        rateAgent: "Оценить оператора",
        writeMessagePlaceholder: "Введите ваше сообщение здесь...",
        sendMessageTip: "Отправить",
        obsoleteBrowser: "Ваш Браузер не поддерживает данную функцию. Новый Браузер Вы можете бесплатно скачать здесь: www.google.com/chrome",
        //-----complain panel
        backButton: "Назад",
        paragraph1: "Вы можете отправить письмо Администратору контакт центра.",
        userEmail: "Email",
        userEmailPlaceholder: "Ваш email",
        userEmailTooltip: "Введите действительный email",
        writeComplainLabel: "Текст письма",
        writeComplainPlaceholder: "Введите текст письма здесь...",
        sendComplain: "Отправить",
        sentComplainInfo: "Ваше сообщение отправлено",
        //-----offline panel
        paragraph2: "Пожалуйста, отправьте нам сообщение, мы свяжимся с вами в ближайшее время.",
        writeEmailLabel: "Текст письма",
        writeEmailPlaceholder: "Введите текст письма здесь...",
        attachLabel: "Приложить файл",
        sendEmail: "Отправить",
        //-----session timeout panel
        paragraph3: "Время сессии истекло.</br>Ваш диалог завершен.",
        sendChatLabel: "Хотите отправить диалог?",
        newChatButton: "Новый чат"
    },
    en: {
        buttonText: "Need help?",
        closeChatText: "User finished dialog.",
        transferError: "Error occured while transfer the file: ",
        sessionTimeout: "Session timeout. Your dialogue is over.",
        //-----prechat panel
        userName: "Name",
        userNamePlaceholder: "Your name",
        userNameTooltip: "Fill in the required fields",
        userTel: "Phone",
        userTelPlaceholder: "+380",
        userTelTooltip: "Enter number in correct format",
        userQuestion: "Question",
        userQuestionPlaceholder: "Your question",
        userLanguage: "Chat language",
        acceptLabel: "I accept",
        termsLink: "terms and conditions",
        closeChatButton: "Close",
        startChatButton: "Start chat",
        checkbTooltip: "Accept terms & conditions",
        //-----chat panel
        resizeTip: "Resize",
        minimizeTip: "Minimize",
        newWindowTip: "Open in new window",
        closeTip: "End chat",
        soundOffTip: "Turn sound off",
        soundOnTip: "Turn Sound on",
        soundOffinfo: "Sound turned off",
        soundOninfo: "Sound turned on",
        writeComplain: "Complain",
        sendFileTip: "Send file",
        sendChatTip: "Send chat via email",
        rateAgent: "Rate agent",
        writeMessagePlaceholder: "Write your message here...",
        sendMessageTip: "Send",
        obsoleteBrowser: "Your Browser is not support that feature. You can download a new browser here: www.google.com/chrome",
        //-----complain panel
        backButton: "Back",
        paragraph1: "You can send a message to the Contact Center Administrator.",
        userEmail: "Email",
        userEmailPlaceholder: "Your email",
        userEmailTooltip: "Enter valid email",
        writeComplainLabel: "Message",
        writeComplainPlaceholder: "Your message here...",
        sendComplain: "Send",
        sentComplainInfo: "Your message sent",
        //-----offline panel
        paragraph2: "Please leave us a message, we will contact you shortly.",
        writeEmailLabel: "Message",
        writeEmailPlaceholder: "Your message here...",
        attachLabel: "Attach file",
        sendEmail: "Send",
        //-----session timeout panel
        paragraph3: "This session is over.</br>Your dialogue is finished",
        sendChatLabel: "Would you like to send dialogue?",
        newChatButton: "New chat"
    },
    uk: {
        buttonText: "Допомогти?",
        closeChatText: "Відвідувач закінчив діалог.",
        transferError: "Під час передачі файлу виникла помилка: ",
        sessionTimeout: "Час сессії закінчився. Ваш діалог завершено.",
        //-----prechat panel
        userName: "Ім'я",
        userNamePlaceholder: "Ваше ім'я",
        userNameTooltip: "Заповніть обов'язкові поля",
        userTel: "Телефон",
        userTelPlaceholder: "+380",
        userTelTooltip: "Введіть номер у правильному форматі",
        userQuestion: "Запитання",
        userQuestionPlaceholder: "Ваше запитання",
        userLanguage: "Мова спілкування",
        acceptLabel: "Я приймаю",
        termsLink: "умови користування",
        closeChatButton: "Закрити",
        startChatButton: "Розпочати чат",
        checkbTooltip: "Прийміть правила користування",
        //-----chat panel
        resizeTip: "Розширити",
        minimizeTip: "Згорнути",
        newWindowTip: "Відкрити у новому вікні",
        closeTip: "Закінчити діалог",
        soundOffTip: "Вкл. звуковий сигнал",
        soundOnTip: "Вимк. звуковий сигнал",
        soundOffinfo: "Звук вимкнено",
        soundOninfo: "Звук включений",
        writeComplain: "Поскаржитися",
        sendFileTip: "Відправити файл",
        sendChatTip: "Відправити чат по email",
        rateAgent: "Оцінити оператора",
        writeMessagePlaceholder: "Напишіть ваше повідомлення тут...",
        sendMessageTip: "Відправити",
        obsoleteBrowser: "Ваш Браузер не підтримує цю функцію. Ви можете завантажити новий Браузер звідси: www.google.com/chrome",
        //-----complain panel
        backButton: "Назад",
        paragraph1: "Ви маєте можливість надіслати листа Адміністратору контакт центру.",
        userEmail: "Email",
        userEmailPlaceholder: "Ваш email",
        userEmailTooltip: "Введіть дійсний email",
        writeComplainLabel: "Текст листа",
        writeComplainPlaceholder: "Напишіть текст листа тут...",
        sendComplain: "Відправити",
        //-----offline panel
        paragraph2: "Будьласка, відправте нам повідомлення, ми скоро з вами зв'яжимося.",
        writeEmailLabel: "Текст листа",
        writeEmailPlaceholder: "Напишіть текст листа тут...",
        attachLabel: "Додати файл",
        sendEmail: "Відправити",
        sentComplainInfo: "Ваше повідомлення відправлене",
        //-----session timeout panel
        paragraph3: "Час сессії закінчився.</br> Ваш діалог завершено.",
        sendChatLabel: "Бажаєте відправити діалог?",
        newChatButton: "Новий чат"
    }
};


